### ISSUE TITLE
Consistent naming of archive files?

### ISSUE THREAD

**Issue by mew-cx** [adafruit/Adafruit_CircuitPython_Bundle#100]
Hi,

I realize this is a nit, but is there a reason why the source archives are named as camelcase and underscores, while the mpy archives are named as lowercase and hyphens?  Also, the date appears in different locations between those archive types.

On a case-sensitive OS like Linux, I wind up renaming the camelcase so the files appear together in a list.

A minor thing, I know :-)
cheers
-- mew

**Comment by dhalbert** [comment]
I'm not sure what you mean. Could you point to the files that are named inconsistently. The bundle release assets have consistent naming: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/latest.

**Comment by mew-cx** [comment]
Sure.  These are the filenames I get when downloading w Chrome (dont know if that matters).  The first two are camelcase and underscore, the following three are lowercase and hyphen.  If they use the same capitalization and punct, with the date after "bundle", they would sort together with locale LC_ALL=C.
cheers
-- mew

```
mew@spin:circuitpython !4 0 $ ll
total 2404
-rw-rw-r-- 1 mew mew    8648 Oct 16 20:26 Adafruit_CircuitPython_Bundle-20181016.tar.gz
-rw-rw-r-- 1 mew mew   33414 Oct 16 20:27 Adafruit_CircuitPython_Bundle-20181016.zip
-rw-rw-r-- 1 mew mew  525579 Oct 16 20:26 adafruit-circuitpython-bundle-2.x-mpy-20181016.zip
-rw-rw-r-- 1 mew mew  525579 Oct 16 20:26 adafruit-circuitpython-bundle-3.x-mpy-20181016.zip
-rw-rw-r-- 1 mew mew 1315076 Oct 16 20:26 adafruit-circuitpython-bundle-py-20181016.zip
mew@spin:circuitpython !5 0 $ 
```

**Comment by dhalbert** [comment]
Ah, I see. The capitalized files are not named by us, but are generated automatically by GitHub when we make a release (highlighted below). There's no way to turn those off. We don't actually recommend that you download those files to get the source because they contain stuff that you don't want or need in your lib directory on CIRCUITPY. The "bundle-py" contains the .py versions that correspond to the .mpy versions.

![image](https://user-images.githubusercontent.com/2847802/47061675-828c3780-d1a0-11e8-9623-6d63ec70db52.png)

**Comment by mew-cx** [comment]
Ah, ok.  Thanks.
