### ISSUE TITLE
asyncio not being included in bundle due to package_folder_prefix

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#356]
See https://github.com/adafruit/circuitpython-build-tools/issues/82, which is the fundamental issue.

**Comment by FoamyGuy** [comment]
Thinking about this from a different angle. Is there a specific reason that the module is named `asyncio` instead of `adafruit_asyncio`? My guess is perhaps this was done to equalize the import and as much of the API as possible between CircuitPython and CPython. 

But in other libraries that are similar modeled after and contain a subset of APIs of CPython modules they do have the `adafruit_` in their name, and examples use `as` in the import to change the name to match CPython. The one that comes to mind for me is: https://github.com/adafruit/Adafruit_CircuitPython_Requests which has the module named `adafruit_requests` and imports in the examples are done like this:
```
import adafruit_requests as requests
```

Maybe it would make sense to add the `adafruit_` prefix to asyncio instead of making an exception for it in the bundle / build tools command?
