### ISSUE TITLE
Bundle being rebuilt with no library changes

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Bundle#432]
Last two nightly bundle builds did not have any library changes. I can't remember: is the bundle rebuilt no matter what? The cron job is updating other things, but if there are no changes, should it still rebuild the bundle? Maybe this is new due to recent CI changes, or maybe I am just not remembering.

**Comment by Neradoc** [comment]
It really shouldn't, it seems it has been happening since 10 or 11 Dec 2022:
https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/tag/20221211
It has no "updated libraries" or "new libraries" section, and the following release seemingly has 100% identical content.

**Comment by tekktrik** [comment]
I'll check on this tonight!

**Comment by tekktrik** [comment]
Looking at the relevant code and the timeframe, this lines up with the change I made to publish for auto-tallying library downloads.  It looks like because it makes a commit and push for that markdown page, it causes a release to happen now since "updates" were made.  I can work on changing that, if having what is now effectively a daily bundle release is undesirable.

**Comment by dhalbert** [comment]
I think it would be good to suppress releases when there are no changes. It reduces needless downloads, both automatic by `circup`, and manual by people who think something might have changed. Thanks for the diagnosis~
