### ISSUE TITLE
Should MAX7219 be supported in CircuitPython

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/Adafruit_CircuitPython_Bundle#5]
I have been working on an implementation of max7219 spi that is compatible with CircuitPython and is  based the oled driver.  I see the micropython version of max7219 and documentation in the CircuitPython API document for it, but no code.  Did you decide not to implement it?  Does my driver make more sense in the Community Bundle?  I need some direction.

**Comment by tannewt** [comment]
Its not intentional. I just haven't gotten to it. We do sell the chip ourselves so I'd be interested in having it under our official support.

The code for those docs is here: https://github.com/adafruit/micropython-adafruit-max7219/blob/master/max7219.py

How about you modify that code to work on CircuitPython and I'll create a separate adafruit repo where it can live? We can also add it to the official bundle then.

**Comment by mrmcwethy** [comment]
I like that.  I have a working version for Matrix 8x8.  Also I was thinking that a major feature of the MAX7219 chip is the 8 digit 7-segment LED driver.  I was thinking we could add the API for that as well.
Mike 

    On Friday, August 11, 2017 5:11 PM, Scott Shawcroft <notifications@github.com> wrote:
 

 Its not intentional. I just haven't gotten to it. We do sell the chip ourselves so I'd be interested in having it under our official support.The code for those docs is here: https://github.com/adafruit/micropython-adafruit-max7219/blob/master/max7219.pyHow about you modify that code to work on CircuitPython and I'll create a separate adafruit repo where it can live? We can also add it to the official bundle then.—

**Comment by tannewt** [comment]
Fixed by 8881d5a16d31d2df9d671887574e041e0fde6e37
